version: '3'
services:
  reverse-proxy:
    build:
      context: ./ReverseProxy
    ports:
      - 81:80
      - 443:443
  app:
    build:
      context: ./App
    ports:
      - 3000:3000 
    volumes:
      - ./App/NodeApplication:/var/www
  db:
    build:
      context: ./DB
    ports:
      - 27017:27017
    volumes:
      - /home/pbrewer/appdatabase:/data/db
